### ISSUE TITLE
Possible issue with `catch_unwind` in renderer for unit tests

### ISSUE THREAD

**Issue by b-ma** [orottier/web-audio-api-rs#522]
Hey,

I just realized today that the `catch_unwind` in unit test can probably lead to false positive tests

```rs
match panic::catch_unwind(catch_me) {
    Ok(tail_time) => (true, tail_time),
    Err(e) => {
        node.outgoing_edges.clear();
        scope.report_error(e);
        (false, false)
    }
}
```

For example, if we want an empty buffer as expected result, but the node just crashes (and is removed from graph), then the resulting buffer is empty so the test is passing... And we can only see the problem if we run the tests with the `--nocapture` flag.

I checked very very rapidly and maybe we already have such issues, e.g. `node::waveshaper::tests::test_user_defined_options` (TBC)

**Comment by orottier** [comment]
That's a very good point. 
I can propagate the panic when testing so it always shows up. Plus an option to disable that because in some tests we actually test the onerror feature

**Comment by orottier** [comment]
Indeed this issue occurs in 2 waveshaper tests:

```
---- node::waveshaper::tests::change_none_for_curve_after_build stdout ----
thread 'node::waveshaper::tests::change_none_for_curve_after_build' panicked at src/node/waveshaper.rs:328:9:
assertion failed: samples_in.iter().all(|channel|
        channel.as_ref().len() == self.processor.input_frames_next())
Panic occurred in Audio Processor: 'assertion failed: samples_in.iter().all(|channel|
        channel.as_ref().len() == self.processor.input_frames_next())'. Removing node from graph.
thread 'node::waveshaper::tests::change_none_for_curve_after_build' panicked at src/events.rs:195:13:
ErrorEvent { message: "assertion failed: samples_in.iter().all(|channel|\n        channel.as_ref().len() == self.processor.input_frames_next())", error: Any { .. }, event: Event { type_: "ErrorEvent" } }

---- node::waveshaper::tests::test_user_defined_options stdout ----
thread 'node::waveshaper::tests::test_user_defined_options' panicked at src/node/waveshaper.rs:328:9:
assertion failed: samples_in.iter().all(|channel|
        channel.as_ref().len() == self.processor.input_frames_next())
Panic occurred in Audio Processor: 'assertion failed: samples_in.iter().all(|channel|
        channel.as_ref().len() == self.processor.input_frames_next())'. Removing node from graph.
thread 'node::waveshaper::tests::test_user_defined_options' panicked at src/events.rs:195:13:
ErrorEvent { message: "assertion failed: samples_in.iter().all(|channel|\n        channel.as_ref().len() == self.processor.input_frames_next())", error: Any { .. }, event: Event { type_: "ErrorEvent" } }
